/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { AutoRouterRoute } from '@elegant-router/types';

export const routes: AutoRouterRoute[] = [
  {
    name: 'Root',
    path: '/',
    redirect: '/home',
  },
  {
    name: 'NotFound',
    path: '/:pathMatch(.*)*',
    layout: 'base',
    component: '404',
  },
  {
    name: '403',
    path: '/403',
    layout: 'base',
    component: '403',
  },
  {
    name: '404',
    path: '/404',
    layout: 'base',
    component: '404',
  },
  {
    name: '500',
    path: '/500',
    layout: 'base',
    component: '500',
  },
  {
    name: 'Home',
    path: '/home',
    layout: 'base',
    component: 'Home',
  },
  {
    name: 'Login',
    path: '/login',
    layout: 'base',
    component: 'Login',
  },
  {
    name: 'Test',
    path: '/test',
    layout: 'base',
    component: 'Test',
  },
];
