/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteKey, RoutePathMap } from '@elegant-router/types';

const routePathMap: RoutePathMap = {
  Root: '/',
  NotFound: '/:pathMatch(.*)*',
  '403': '/403',
  '404': '/404',
  '500': '/500',
  Home: '/home',
  Login: '/login',
  Test: '/test',
};

export function getRoutePath(key: RouteKey) {
  return routePathMap[key];
}
