/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      hideInMenu: true,
    },
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      icon: 'HomeFilled',
    },
  },
  {
    name: 'test',
    path: '/test',
    component: 'layout.base',
    meta: {
      title: 'test',
    },
    children: [
      {
        name: 'test_test1',
        path: '/test/test1',
        component: 'view.test_test1',
        meta: {
          title: 'test_test1',
        },
      },
      {
        name: 'test_test2',
        path: '/test/test2',
        component: 'view.test_test2',
        meta: {
          title: 'test_test2',
        },
      },
    ],
  },
];
