/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '页面不存在',
      hideInMenu: true,
    },
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '首页',
      icon: 'HomeFilled',
    },
  },
  {
    name: 'login',
    path: '/login',
    component: 'layout.blank$view.login',
    meta: {
      title: '登录',
      hideInMenu: true,
    },
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base$view.profile',
    meta: {
      title: '个人资料',
      hideInMenu: true,
    },
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: '系统设置',
      hideInMenu: true,
    },
  },
  {
    name: 'test',
    path: '/test',
    component: 'layout.base',
    meta: {
      title: '测试页面',
    },
    children: [
      {
        name: 'test_test1',
        path: '/test/test1',
        component: 'view.test_test1',
        meta: {
          title: '测试页面1',
        },
      },
      {
        name: 'test_test2',
        path: '/test/test2',
        component: 'view.test_test2',
        meta: {
          title: '测试页面2',
        },
      },
    ],
  },
];
